name: s2i with buildpacks
on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: 'Container Image Name'
        required: true
        type: string
env:
    IMAGE_TAGS: ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: source to container image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: install pack cli
        run: brew install buildpacks/tap/pack

      - name: setup docker
        uses: docker-practice/actions-setup-docker@master
      
      - name: check docker
        run: |
          set -x
          docker version

      - name: build
        run: |
          set -x 

          pack build ${{ inputs.IMAGE_NAME }} --buildpack paketo-buildpacks/dotnet-core --builder paketobuildpacks/builder:base --tag ${{ env.IMAGE_TAGS }}
      
      - name: list images
        run: |
          docker ps
      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ inputs.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
          extra-args: |
            --disable-content-trust
      
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"